### ISSUE TITLE
TTS Play

### ISSUE THREAD

**Issue by ItsTatsuya** [CDE90/VCRoles#68]
Bot says, it played the TTS message, but it didn't

**Comment by CDE90** [comment]
Hey, thanks for raising this, there's been a few reports about this, so probably time that I have a dive into what's wrong. I'll update you when I find anything

**Comment by ItsTatsuya** [comment]
sounds good

**Comment by ItsTatsuya** [comment]
seems that it is fixed, so closing the issue
